1. What are data structures, and why are they important?
   - Data structures are organized ways to store, manage, and organize data for efficient access and modification. They are important because they affect the performance of algorithms and applications by optimizing storage, retrieval, and manipulation of data.


2. Explain the difference between mutable and immutable data types with examples
   - Mutable data types can be changed after creation, e.g., lists (``) can have elements added or removed. Immutable data types cannot be changed once created, e.g., strings ("hello") or tuples ((1, 2, 3)).


3. What are the main differences between lists and tuples in Python?
   - Lists are mutable, allowing modification of elements, and use square brackets. Tuples are immutable, fixed size, and use parentheses. Lists consume more memory and support more operations; tuples are faster and used for fixed data.


4. Describe how dictionaries store data
   - Dictionaries store data as key-value pairs using a hash table underneath. Keys are unique, hashable, and map to values, enabling fast lookups by key.


5. Why might you use a set instead of a list in Python
   - Sets are used instead of lists when you need to ensure unique values and perform fast membership tests or operations like unions and intersections, as sets automatically discard duplicates.


6. What is a string in Python, and how is it different from a list
   - A string in Python is an immutable sequence of characters. Unlike lists, which are mutable sequences of any data type, strings are fixed and cannot be changed once created.


7. How do tuples ensure data integrity in Python?
   - Tuples ensure data integrity by being immutable, preventing accidental modification after creation, which is useful for fixed data like coordinates or constants.


8. What is a hash table, and how does it relate to dictionaries in Python?
   - A hash table is a data structure that uses a hash function to map keys to buckets for fast data retrieval. Dictionaries in Python use hash tables to enable average O(1) time complexity for lookups.


9. Can lists contain different data types in Python
   - Yes, lists in Python can contain elements of different data types, e.g., [1, "a", 3.5].


10. Explain why strings are immutable in Python
    - Strings are immutable in Python to optimize performance and safety, allowing sharing and reuse of string objects without unexpected modifications.


11. What advantages do dictionaries offer over lists for certain tasks
    - Dictionaries allow fast access to values by keys, unlike lists which require linear search. This is advantageous for lookups, insertions, and deletions by a unique identifier.


12. Describe a scenario where using a tuple would be preferable over a list
    - Using a tuple is preferable when the data should remain constant, such as representing fixed attributes of an entity, e.g., an (x, y) coordinate pair.


13. How do sets handle duplicate values in Python?
    - Sets automatically discard duplicate values, maintaining only unique elements without repetition.


14. How does the “in” keyword work differently for lists and dictionaries?
    - The in keyword checks for presence in both lists and dictionaries but in dictionaries it checks keys, whereas in lists it checks values by scanning elements.

15. Can you modify the elements of a tuple? Explain why or why not.
    - You cannot modify elements of a tuple because tuples are immutable, designed to prevent any changes after creation for data consistency.


16. What is a nested dictionary, and give an example of its use case?
    - A nested dictionary is a dictionary containing dictionaries as values, useful for complex hierarchical data like JSON. Example: {"person": {"name": "Alice", "age": 30}}.


17. Describe the time complexity of accessing elements in a dictionary.
    - Accessing elements in a dictionary has average time complexity O(1) due to the hash table, but worst case O(n) if many keys collide.


18. In what situations are lists preferred over dictionaries.
    - Lists are preferred over dictionaries when order and sequence matter, or when only numerical indices are needed, such as storing items in order.


19. Why are dictionaries considered unordered, and how does that affect data retrieval?
    - Dictionaries are considered unordered until Python 3.7+ where insertion order is preserved, but conceptually they rely on hashing, so key order shouldn't be expected. This affects retrieval by key only, not by position.


20. Explain the difference between a list and a dictionary in terms of data retrieval.
    - Lists are accessed by integer index sequentially, resulting in O(n) search for values. Dictionaries access values directly by unique keys, offering much faster lookup (O(1)) when keys are known.

In [1]:
# Write a code to create a string with your name and print it

name = "Akash"
print(name)

Akash

In [ ]:
# Write a code to find the length of the string "Hello World"

text = "Hello World"
print(len(text))

11

In [ ]:
# Write a code to slice the first 3 characters from the string "Python Programming"

s = "Python Programming"
print(s[:3])

Pyt

In [ ]:
# Write a code to convert the string "hello" to uppercase

s = "hello"
print(s.upper())

HELLO

In [ ]:
# Write a code to replace the word "apple" with "orange" in the string "I like apple"

s = "I like apple"
print(s.replace("apple", "orange"))

I like orange

In [ ]:
# Write a code to create a list with numbers 1 to 5 and print it

lst = [1, 2, 3, 4, 5]
print(lst)

[1, 2, 3, 4, 5]

In [ ]:
# Write a code to append the number 10 to the list [1, 2, 3, 4]

lst = [1, 2, 3, 4]
lst.append(10)
print(lst)

[1, 2, 3, 4, 10]

In [ ]:
# Write a code to remove the number 3 from the list [1, 2, 3, 4, 5]

lst = [1, 2, 3, 4, 5]
lst.remove(3)
print(lst)

[1, 2, 4, 5]

In [ ]:
# Write a code to access the second element in the list ['a', 'b', 'c', 'd']

lst = ['a', 'b', 'c', 'd']
print(lst[1])

b

In [ ]:
# Write a code to reverse the list [10, 20, 30, 40, 50]

lst = [10, 20, 30, 40, 50]
lst.reverse()
print(lst)

[50, 40, 30, 20, 10]

In [ ]:
# Write a code to create a tuple with the elements 100, 200, 300 and print it

t = (100, 200, 300)
print(t)

(100, 200, 300)

In [ ]:
# Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow')

t = ('red', 'green', 'blue', 'yellow')
print(t[-2])

blue

In [ ]:
# Write a code to find the minimum number in the tuple (10, 20, 5, 15)

t = (10, 20, 5, 15)
print(min(t))

5

In [ ]:
# Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit')

t = ('dog', 'cat', 'rabbit')
print(t.index("cat"))

1

In [ ]:
# Write a code to create a tuple containing three different fruits and check if "kiwi" is in it

t = ("apple", "banana", "mango")
print("kiwi" in t)

False

In [ ]:
# Write a code to create a set with the elements 'a', 'b', 'c' and print it

s = {'a', 'b', 'c'}
print(s)

{'a', 'c', 'b'}

In [ ]:
# Write a code to clear all elements from the set {1, 2, 3, 4, 5}

s = {1, 2, 3, 4, 5}
s.clear()
print(s)

set()

In [ ]:
# Write a code to remove the element 4 from the set {1, 2, 3, 4}

s = {1, 2, 3, 4}
s.remove(4)
print(s)

{1, 2, 3}

In [ ]:
# Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}

a = {1, 2, 3}
b = {3, 4, 5}
print(a.union(b))

{1, 2, 3, 4, 5}

In [ ]:
# Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}

a = {1, 2, 3}
b = {2, 3, 4}
print(a.intersection(b))

{2, 3}

In [2]:
# Write a code to create a dictionary with the keys "name", "age", and "city", and print it

d = {"name": "Akash", "age": 29, "city": "Nagpur"}
print(d)

{'name': 'Akash', 'age': 29, 'city': 'Nagpur'}

In [ ]:
# Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}

d = {'name': 'John', 'age': 25}
d["country"] = "USA"
print(d)

{'name': 'John', 'age': 25, 'country': 'USA'}

In [ ]:
# Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}

d = {'name': 'Alice', 'age': 30}
print(d["name"])

Alice

In [ ]:
# Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}

d = {'name': 'Bob', 'age': 22, 'city': 'New York'}
del d["age"]
print(d)

{'name': 'Bob', 'city': 'New York'}

In [ ]:
# Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}

d = {'name': 'Alice', 'city': 'Paris'}
print("city" in d)

True

In [ ]:
# Write a code to create a list, a tuple, and a dictionary, and print them all

lst = [1, 2, 3]
t = (4, 5, 6)
d = {"a": 1, "b": 2}
print(lst, t, d)

[1, 2, 3] (4, 5, 6) {'a': 1, 'b': 2}

In [ ]:
# Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the result

import random
lst = random.sample(range(1, 101), 5)
lst.sort()
print(lst)

[4, 10, 32, 40, 92]

In [ ]:
# Write a code to create a list with strings and print the element at the third index

lst = ["one", "two", "three", "four", "five"]
print(lst[3])

four

In [ ]:
# Write a code to combine two dictionaries into one and print the result

d1 = {"a": 1, "b": 2}
d2 = {"c": 3, "d": 4}
d1.update(d2)
print(d1)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [ ]:
# Write a code to convert a list of strings into a set

lst = ["apple", "banana", "apple", "mango"]
s = set(lst)
print(s)

{'mango', 'banana', 'apple'}